### ISSUE TITLE
Page des espaces de travail

### ISSUE THREAD

**Issue by ThebaultLouis** [uffoltzl/challenge_atos#2]

**Comment by ThebaultLouis** [comment]
Espaces de travail
Station de métro
Arrêt de bus

**Comment by uffoltzl** [comment]
mettre en avant les espaces avec une petite empreinte carbone (l'icone de ces espaces doit être plus gros que celui des autres)
- ces espaces sont ceux qui sont proches de la maison de l'employé
- ces espaces peuvent aussi avoir été spécialement sélectionné par nos soins, par exemple, un espace qui est très bien isolé thermiquement

**Comment by uffoltzl** [comment]
- ajouter une fonction de recherche (avec filtre)
- pouvoir recentrer
- voir les prix de reduction ressortir sur la carte
