### ISSUE TITLE
Détail d'un espace de travail

### ISSUE THREAD

**Issue by ThebaultLouis** [uffoltzl/challenge_atos#3]
Voir les fluctuations du prix
Suggérer des horaires

Mix entre oui.sncf et kraken (site de crypto)

**Comment by uffoltzl** [comment]
Green : 
- lien vers un site de covoiturage (blablacar ou un  forum) > à ne pas coder mais on voit le front associé
- stats green disponible : faire une comparaison entre les différents moyens de transport (vélo, transport en commun, voiture) sur les points > temps mis depuis chez soi, prix (essence, parking, ticket de métro), bilan carbone

**Comment by uffoltzl** [comment]
Voir un bouton réserver, pas besoin d'aller plus loin, on suppose que ça envoie sur une page pour réserver le jour/heure...
